# Generated by Django 2.1.4 on 2019-02-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='главная',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('услуги', models.TextField(blank=True)),
                ('специалисты', models.TextField(blank=True)),
                ('диагностика', models.TextField(blank=True)),
            ],
        ),
    ]
