# Generated by Django 2.1.4 on 2019-03-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='главная',
        ),
    ]
