# Generated by Django 2.1.4 on 2019-03-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faun', '0002_auto_20190303_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main',
            name='diagnostics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main',
            name='specialists',
            field=models.TextField(blank=True),
        ),
    ]
