# Generated by Django 2.1.4 on 2019-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190302_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='docto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoname', models.TextField()),
                ('photo', models.ImageField(upload_to='doctor/static/css')),
                ('name', models.TextField()),
                ('information', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
