# Generated by Django 2.1.4 on 2019-03-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20190302_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photoname',
        ),
    ]
